---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: "Delete SSH Host Keys"
      file:
        path: "{{item}}"
        state: absent
      with_fileglob:
        - "/etc/ssh/ssh_host*"
